# Generated by Django 2.1.1 on 2020-04-21 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user_pk']},
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('user', 'user_pk')},
        ),
    ]
