# Generated by Django 2.1.1 on 2020-05-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_api', '0004_auto_20200515_2055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
