# Generated by Django 2.1.1 on 2020-05-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework_api', '0006_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
